version: 1.0.{build}
image: Visual Studio 2017
  

install:
  - docker pull metasyn/nim-servercore

build_script:
  - docker run -v C:\projects\nim-flaschen-taschen:C:\Temp metasyn/nim-servercore 'cd C:\Temp\nim_flaschen_taschen; nimble install; nimble test'
